import type { Metadata } from "next";
import Box from '@mui/material/Box';
import { Toolbar } from "@mui/material";
import SideBar from "@/component/layout/SideBar";
import TopBar from "@/component/layout/TopBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Box sx={{ display: 'flex' }}>
          <TopBar></TopBar>
          <SideBar></SideBar>
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <Toolbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
